disabled_rules:
  - trailing_comma
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - lib/.build
  - frontend

custom_rules:
  disable_print:
    included: ".*\\.swift"
    name: "print usage"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Prefer os_log over print"
    severity: error
