name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app:
    runs-on: macos-latest

    steps:
      - name: Compile
        run: xcodebuild -scheme ShitheadenApp -configuration Release -project ShitheadenApp.xcodeproj archive -archivePath ./Shitheaden.xcarchive
  swift:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build
        run: docker build . -t tomasharkema7/shitheaden
      - name: Deploy
        run: docker push tomasharkema7/shitheaden
