name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
#     runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t tomasharkema7/shitheaden
    - name: Deploy
      run: docker push tomasharkema7/shitheaden
